### ISSUE TITLE
make setters private?

### ISSUE THREAD

**Issue by grindhold** [OParl/liboparl#2]
liboparl's primary use is to build clients. But it is also thinkable to use liboparl's validation functions to validate objects before they leave an oparl-server. Thus it would be necessary to let the users set all attributes. making them private/internal would end up in a even cleaner API. What does the OParl team say?

**Comment by eFrane** [comment]
I vote for private setters as OParl is currently readonly anyway and setters are if not wrong at least an anti pattern for something that cannot be written to in most cases.

**Comment by grindhold** [comment]
so be it
