### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by konstin** [OParl/liboparl#25]
There have been multiple important changes since 0.2.1, most importantly c3364664ff2531dd0f1ce1d5426ba71e60640a4b. This means that returning status codes from python requires using master, which is undesirable.

A 0.3.0 release would also allow using the latest improvements in the validator.

**Comment by eFrane** [comment]
There will soon be a "new stable" 0.4.0 Release. However this is currently still blocked by a minor inconvenience known as f_pageable_sequence or more generally speaking the speed at which liboparl can usefully operate on large datasets.

**Comment by grindhold** [comment]
First a little something on versioning:

Stable versions are released as <major>.<even minor>.<revision>
Unstable versions are released as <major>.<odd minor>.<revision>

As we have a working API right now in master, i will release the current master as 0.4.0.
As soon as f_pageable_sequence is usable and testable we should release a developer release 0.5.0 with the sequencing.
When feedback goes well, we will release the version with sequencing as 0.6.0 in a stable release.

When i distill the commitlog for 0.4.0, it comes down to the following changelog:

  * Introducing Docker Support
  * API optimizations
  * Make error messages more helpful for debugging
  * Improved examples and documentation
  * Introducing hydrate-method to directly convert
    json to liboparl-objects
  * Refining object resolver internals
  * Consolidate parsing of primitive types
  * Introducing a non-strict mode of the client that
    yields warnings instead of errors in case single
    objects cannot be parsed/resolved correctly
  * Improved object validation logic
  * Internationalization
  * Localisations for en_US and de_DE
  * Fixed several bugs

If i am missing something important, please review and comment within the next 25 minutes.

**Comment by grindhold** [comment]
https://github.com/OParl/liboparl/releases/tag/0.4.0
