### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by konstin** [OParl/liboparl#5]
Due to the big number of network requests that has to be made and the unavoidable waiting times it gives important performance improvements to parallelize API request. Therefore I'ld like to know if or how the library can be used with multi-threading. The answer should be added to the documentation.

**Comment by grindhold** [comment]
konstin: the library emits the resolve_url signal everytime it needs something from teh interwebs. this lets you decide how to handle/queue/parallelize the upcoming requests in your application code. the parse methods (and thus writing operations) are called once per object. when you implement an `OParl.Cache` in your code, this can be regarded as guaranteed, so i think no additional locks are necessary.

**Comment by grindhold** [comment]
soooo. i now ran into (and immediately fixed) the first race condition problem.
i currently develop a threaded program against the lib, so this will be
tested as of now.
i am closing this issue as it is not an open question anymore. some work on
thread-safety has to happen.
