### ISSUE TITLE
Build failed - Test.set_nonfatal_assertions / Test.skip

### ISSUE THREAD

**Issue by michamilz** [OParl/liboparl#9]
After running ninja, i got the following output:

`
[15/35] Compiling Vala source ../test/main.vala ../test/fixtures.vala ../test/object.vala ../test/system.vala ../...ting.vala ../test/agenda_item.vala ../test/paper.vala ../test/consultation.vala ../test/file.vala oparl-0.2.vapi.  
FAILED: oparl_test@exe/main.c oparl_test@exe/fixtures.c oparl_test@exe/object.c   oparl_test@exe/system.c oparl_test@exe/body.c oparl_test@exe/legislative_term.c   oparl_test@exe/location.c oparl_test@exe/organization.c oparl_test@exe/person.c   oparl_test@exe/membership.c oparl_test@exe/meeting.c oparl_test@exe/agenda_item.c   oparl_test@exe/paper.c oparl_test@exe/consultation.c oparl_test@exe/file.c  
valac '--debug' '-d' 'oparl_test@exe' '-C' '--pkg' 'glib-2.0' '--pkg' 'gobject-2.0' '--pkg' 'json-glib-1.0' '--pkg' 'gio-2.0' ../test/main.vala ../test/fixtures.vala ../test/object.vala ../test/system.vala ../test/body.vala ../test/legislative_term.vala ../test/location.vala ../test/organization.vala ../test/person.vala ../test/membership.vala ../test/meeting.vala ../test/agenda_item.vala ../test/paper.vala ../test/consultation.vala ../test/file.vala oparl-0.2.vapi  
../test/main.vala:28.13-28.40: error: The name `set_nonfatal_assertions' does not exist in the context of `GLib.Test'  
            Test.set_nonfatal_assertions();  
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
../test/agenda_item.vala:82.17-82.25: error: The name `skip' does not exist in the context of `GLib.Test'  
                Test.skip("Due to fixture conflict with file_sane fixture");  
                ^^^^^^^^^  
Compilation failed: 2 error(s), 0 warning(s)  
[16/35] Compiling c object 'oparl-0.2@sha/oparl-0.2@sha_file.c.o'  
ninja: build stopped: subcommand failed.  
`

meson output

`
The Meson build system  
Version: 0.38.1  
Source dir: /xxx/libs/liboparl  
Build dir: /xxx/libs/liboparl/build  
Build type: native build  
Project name: oparl  
Native vala compiler: valac (valac 0.22.1)  
Native c compiler: cc (gcc 4.8.4)  
Build machine cpu family: x86_64  
Build machine cpu: x86_64  
Found pkg-config: /usr/bin/pkg-config (0.26)  
Native dependency glib-2.0 found: YES 2.40.2  
Native dependency gobject-2.0 found: YES 2.40.2  
Native dependency json-glib-1.0 found: YES 0.16.2  
Native dependency gio-2.0 found: YES 2.40.2  
Program g-ir-compiler found: YES (/usr/bin/g-ir-compiler)  
Program valadoc found: YES (/usr/bin/valadoc)  
Build targets in project: 4  
`

meson 0.38.1
ninja 1.7.2
Vala 0.22.1

**Comment by grindhold** [comment]
this is most likely due to your compiler version which is pretty old.
it most likely tries to link against an ancient libglib-2.0 which does
not provide the method in the error message.

we shall resolve this by adding same minimum versions to the buildfile.

**Comment by grindhold** [comment]
added a rudimentary compiler version-check
